from os import getenv

FASTAPI_LOGIN_TOKEN_VALUE = getenv("FASTAPI_LOGIN_TOKEN")

SESSION_MIDDLEWARE_TOKEN_NAME = getenv("SESSION_MIDDLEWARE_TOKEN")

if FASTAPI_LOGIN_TOKEN_VALUE is None:
    print("FASTAPI_LOGIN_TOKEN is not set")

if SESSION_MIDDLEWARE_TOKEN_NAME is None:
    print("SESSION_MIDDLEWARE_TOKEN is not set")
